version: "3"
services:
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    hostname: selenium
    ports:
      - "6559:5900"
      - "6544:4444"

  nginx:
    image: nginx:latest
    ports:
      - "6580:80"
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./tests/static:/static
    depends_on:
      - selenium

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - .:/code
    depends_on:
      - selenium
      - nginx
    environment:
      - SELENIUM_PROTOCOL=http
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - SELENIUM_START_URL=http://nginx
