version: "3"
services:
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    hostname: selenium
    ports:
      - "6559:5900"
      - "6544:4444"

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    ports:
      - "6580:8000"
    volumes:
      - .:/code
    depends_on:
      - selenium
    environment:
      - SELENIUM_DRIVER_URL=http://selenium:4444
      - SELENIUM_START_URL=http://php:8000
