name: ci
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
        options: --add-host=host.docker.internal:host-gateway
        ports:
          - 4444:4444
    steps:
      - uses: actions/checkout@v4
      - run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        id: composer-cache
      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - run: composer install --prefer-dist --no-interaction --optimize-autoloader
      - run: composer check-code
      - run: php -S 0.0.0.0:8000 -t ./tests/static &
      - run: composer test
        env:
          SELENIUM_DRIVER_URL: http://localhost:4444
          SELENIUM_START_URL: http://host.docker.internal:8000
